// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeTourVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "9b0909ef-5ea4-4899-bacf-16c894b87ca0";
        public const string Name = "Code Tour";
        public const string Description = @"Code Tours shows guided tours through any source code base. They are easy to create and easy to use.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
