// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeTourVS
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CodeTourVSPackageString = "a139934a-4daf-44ff-af02-aa018c2ae51f";
        public static Guid CodeTourVSPackage = new Guid(CodeTourVSPackageString);

        public const string CodeTourCmdSetString = "c0f86fe5-9b7c-4a21-8538-512aaef437fd";
        public static Guid CodeTourCmdSet = new Guid(CodeTourCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int GoToStepCommand = 0x0100;
    }
}